name: demo training


on:
   push:
    branches: [main]

   pull_request:
    branches: [main]


jobs:
    setup_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: create file
              run: |
                touch github-action.txt
                ls -la
            - name: print hello world
              run: echo hello world
            - name: display readme file
              run: cat README.md
    build_job:
        needs:
            - setup_job
            
        runs-on: windows-latest
        steps:
            - name: display hello
              run: echo hello
    deploy_job:
        needs: 
            - build_job
        runs-on: macos-latest
        steps:
            - run: echo hello mac                          
     
   
